### ISSUE TITLE
Implement authz permissioning as new command in multisig

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/multisig#14]
* [ ] Implement "enable voting for account using authz"
* [ ] Implement "enable withdraw + withdraw-with-commission using authz"
* [ ] Implement "enable staking using authz"

**Comment by andynog** [comment]
These are the required steps to implement a future workflow with authz to claim rewards and re-delegate. So need to implement the required tx authz with multisig. This is for reference while working on this issue.

### Grant Withdraw rewards

`[binary]  tx authz grant  [grantee_addr] generic --msg-type /cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward --expiration=1651060212 --from=ledgerS --keyring-backend=os --fees=3000ucrbrus --ledger`

### Grant Delegate

`[binary] tx authz grant [grantee_addr] generic --msg-type /cosmos.staking.v1beta1.MsgDelegate --expiration=1651060212 --from=[account] --keyring-backend=os --fees=1000denom`

### Generate Withdraw Rewards Tx

`[binary] tx distribution withdraw-all-rewards --keyring-backend=os --from [granter_address] --fees 1500denom --generate-only > tx.json`

### Execute Withdraw Rewards Tx (grantee on behalf of granter)

`[binary] tx authz exec tx.json --from grantee --keyring-backend=os -y --output json`

### Generate Delegate Tx

`[binary] tx staking delegate [valoper_addr] $([binary] query bank balances [account] -o json | jq '.balances[].amount' | xargs -I % sh -c 'echo $((%-3000));')denom --from account --keyring-backend=os --generate-only > tx_delegate.json`

### Execute Withdraw Rewards Tx (grantee on behalf of granter)

`[binary] tx authz exec tx_delegate.json --from grantee --keyring-backend=os -y`

**Comment by andynog** [comment]
While working in the multisig authz support, realized one thing. I believe the idea is to do a tx authz grant for multiple msg-types (comma separated list) in one shot, like

`multisig tx authz grant <chain name> <key name> <grantee address> <message-types (eg. withdraw,commission,delegate)> [flags]`

but the binary (e.g. gaiad) only allows one message type, like:

`[binary] tx authz grant [grantee_addr] generic --msg-type /cosmos.staking.v1beta1.MsgDelegate --expiration=1651060212 --from=[account] --keyring-backend=os --fees=1000denom`

so any ideas how this could be accomplished ? is there a way to have multiple txs to be signed in one unsigned.json ?

**Comment by andynog** [comment]
Implemented the `tx authz grant` command. I'm now just thinking what would be the right workflow for the remaining parts. I believe the `tx authz exec` will be executed by the grantee (e.g. bot). But the bot doesn't need multisig support as far as I understand. It could generate a tx (e.g. delegate) and execute it via `tx authz exec`.
