### ISSUE TITLE
Delete command or raw delete input parameter change

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/multisig#29]
All commands, including raw cat has the `<chain> <key>` input parameters, so the user gets used to using that.

`raw delete` on the other hand has `<path>` instead because of its advanced functionality of being able to delete a single file.

Scenario:
Michael tested `multisig` by adding two transactions to AWS. Then he wanted to delete them. `raw delete` made it confusing to delete all files one-by-one when he knew exactly which chain,key and possibly `-i` index he wanted to delete.

Possible solution:
new, regular `delete <chain> <key> [-i index]` command.

**Comment by greg-szabo** [comment]
If the index is missing:
A. delete index 0
B. delete all indexes
C. it should delete index 0 if there is only 0. If there is 1/2/etc, it should fail.

**Comment by andynog** [comment]
Implemented a `multisig delete` command

```
Usage:
  multisig delete <chain name> <key name> [flags]

Flags:
  -h, --help        help for delete
  -i, --index int   index of the tx to delete
```
This allows the deletion of files in the S3 bucket just specifying chain name and key name (and index if needed). This is a better user experience than the `raw delete` command where the path needs to be specified and one file can be deleted at a time. 

With the `multisig delete` command all the files under `chain/key/index` will be delete with just one command.
