### ISSUE TITLE
New feature request: more tx types

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/multisig#31]
From Michael:
Can I use the multsig tool to get a unstaking transaction signed?¨
sorry, meant rewards claim

**Comment by greg-szabo** [comment]
so, both...

**Comment by andynog** [comment]
For un-staking, we can add a `tx undelegate` command

For rewards claim, isn't that already supported by the `tx withdraw` command ?

**Comment by andynog** [comment]
closing this since there are/will be individual issues for each additional tx command like #59 or #61
