### ISSUE TITLE
Make the denom part of the config and also retrieve from the chain registry. Tx push should ensure that the txs are using correct denoms

### ISSUE THREAD

**Issue by greg-szabo** [informalsystems/multisig#9]
Ideally denom can become part of the config slash gotten from the chain registry so we never have to worry about it like this

_Originally posted by @ebuchman in https://github.com/informalsystems/multisig/pull/5#discussion_r853702594_

Make the denom part of the config and also retrieve from the chain registry. Tx push should ensure that the txs are using correct denoms

**Comment by andynog** [comment]
we can leverage the chain registry but we'd need the config chain name to match the chain registry folder. For example, in the config we have 

```
[[chains]]
name = "cosmos"
```

but the chain_name for this chain in the registry is `cosmoshub`

```
{
    "$schema": "../chain.schema.json",
    "chain_name": "cosmoshub",
    "chain_id": "cosmoshub-4",

```
